language: go

go:
  - "1.11.x"

env:
  global:
    - GO111MODULE=on

install:
  - go mod download

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic -v ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
